language: ruby
cache: bundler

before_install: 
  - rm Gemfile.lock || true
  - bundle install

install: bundle install --without development

rvm:
 - 2.2.2

before_script:
 - rake db:drop 
 - rake db:create
 - rake db:migrate

script: 
 - rspec spec

branches:
  only:
  - master
  - travis

env: 
 - DB="postgresql"