language: ruby
cache: bundler

install:
  bundle install 

rvm:
 - 2.2.5

before_script:
 - rake db:drop 
 - rake db:create
 - rake db:migrate

script: 
 - rspec spec

branches:
  only:
  - master

env: 
 - DB="postgresql"
